spring.application.name=AgriFinanceAPIs


spring.datasource.url=jdbc:postgresql://postgres:5432/agritech
spring.datasource.username=postgres
spring.datasource.password=Master

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8080
